id: I17A1E120
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-30T22:16:10.321926'
last_modified: '2022-05-30T22:16:10.321931'
parser: null
source_metadata:
  title: Khenpo Kunzang Palden Series
  language: bo
  description: 'Texts by and about Khenpo Kunzang Palden (kun bzang dpal ldan, 1862–1943),
    alias Khenpo Kunpal, an important disciple of Patrul Rinpoche and author of a
    celebrated commentary on the Bodhicaryāvatāra:'
  volume:
    fC36C:
      title: 'Offering the Flowers of Remembered Kindness: In Praise of the Gracious
        Teacher, Khen Rinpoche Kunpal'
      base_file: fC36C.txt
      order: 1
      parent: Praise
    f47EE:
      title: 'Lightning Bands of Compassion: A Song of Lament for Khenchen Kunzang
        Palden Tupten Chökyi Drakpa'
      base_file: f47EE.txt
      order: 2
      parent: Songs
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
